import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/components/providers";
import styles from './styles.module.scss'
import { Analytics } from "@vercel/analytics/react"
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sakura",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    
    <html lang="en" className={styles.main}>
      <Analytics/>
      <body className={inter.className}>
        <g className="nones">
          <p className="pnones">
            <span className="spans">Sakura</span> on mobile devices? <br></br>
            It&apos;s on the horizon!
          </p>
        </g>
        <Providers>
          {children}
          
        </Providers>
      </body>

    </html>
  );
}
